name: Deployment

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
        name: "Checkout source code"

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          version: 12.x

      - name: Build site
        run: |
          yarn add v1.22.4
          yarn build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1.11
        with:
          publish-dir: "./public"
          production-branch: master
          deploy-message: "${{ github.event.head_commit.message }}"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
